export const productsData = [
  {
    _id: '1',
    name: 'Steel Hammer',
    image: 'https://picsum.photos/200/200',
    brand: 'SteelTools',
    description: 'High-quality hammer for professional use',
    price: 249,
    multiples: 5,
    mainSize: { value: 250, unit: 'mm' },
    variants: [
      { value: 150, unit: 'mm', price: 199 },
      { value: 200, unit: 'mm', price: 229 },
      { value: 300, unit: 'mm', price: 279 },
    ],
  },
  {
    _id: '2',
    name: 'Cordless Drill',
    image: 'https://picsum.photos/200/200',
    brand: 'PowerTech',
    description: 'Cordless drill with two-speed settings',
    price: 14994,
    multiples: 5,
    mainSize: { value: 12, unit: 'V' },
    variants: [
      // { value: 10.8, unit: 'V', price: 1299 },
      // { value: 14.4, unit: 'V', price: 1699 },
    ],
  },
  {
    _id: '5',
    name: 'Interior Wall Paint',
    image: 'https://picsum.photos/200/200',
    brand: 'ColorMax',
    description: 'Premium wall paint with matte finish',
    price: 499,
    multiples: 5,
    mainSize: { value: 5, unit: 'L' },
    variants: [
      { value: 1, unit: 'L', price: 129 },
      { value: 10, unit: 'L', price: 899 },
    ],
  },
  {
    _id: '4',
    name: 'Adjustable Wrench',
    image: 'https://picsum.photos/200/200',
    brand: 'FixIt',
    description: 'Adjustable wrench made of stainless steel',
    price: 179,
    multiples: 5,
    mainSize: { value: 200, unit: 'mm' },
    variants: [
      { value: 150, unit: 'mm', price: 139 },
      { value: 250, unit: 'mm', price: 219 },
    ],
  },
  {
    _id: '5',
    name: 'Lubricant Oil',
    image: 'https://picsum.photos/200/200',
    brand: 'SmoothRun',
    description: 'Multi-purpose industrial lubricant oil',
    price: 349,
    multiples: 5,
    mainSize: { value: 1, unit: 'L' },
    variants: [
      { value: 0.5, unit: 'L', price: 199 },
      { value: 2, unit: 'L', price: 649 },
    ],
  },
];

export const ordersResponse = {
  success: true,
  code: 200,
  message: 'Orders fetched successfully',
  data: [
    {
      orderId: 'ORD123456',
      isCashPayment: true,
      noOfItems: 3,
      date: '2025-04-28',
      time: '14:30',
      amount: 249.99,
    },
    {
      orderId: 'ORD123457',
      isCashPayment: false,
      noOfItems: 5,
      date: '2025-04-27',
      time: '10:15',
      amount: 599.0,
    },
    {
      orderId: 'ORD123458',
      isCashPayment: true,
      noOfItems: 2,
      date: '2025-04-26',
      time: '18:45',
      amount: 149.5,
    },
    {
      orderId: 'ORD123459',
      isCashPayment: false,
      noOfItems: 1,
      date: '2025-04-25',
      time: '09:05',
      amount: 89.99,
    },
  ],
};

export const dataqq = [
  {
    id: '2',
    products_id: '44052',
    product_name: 'Combination Plier - 908',
    product_system_name: 'Pye 908 Combination Plier',
    hsn_code: '82032000',
    description:
      '<h1><strong>About this item</strong></h1><ul><li>ANTI-SLIP HANDLES: Ergonomic grips have a two-tone, anti-slip surface to maximize comfort and provide a secure grip</li><li>HANDLE: The combination plier from pye comes with broad insulated handles that have been made from plastic The material keeps you safe while dealing with electric wires</li><li>PACKAGE CONTAINS: It includes 1 piece of Chrome Vanadium Steel (205mm) Combination Plier</li><li>ANTI-RUST COATING: Clear, anti-rust coating extends the effective life of these pliers, preserving their edge and finish</li><li>COMBINATION TOOL: Built with three functions– a flat gripping surface with fine serrations, a crimping edge and a cutting edge</li></ul><p><br></p>',
    extra_description: '<p><br></p>',
    stock_discount: '2',
    stock: '300',
    display_image:
      'https://pratham.markletech.com/uploads/products/1746254128_Pye 908.PNG',
    mrp: '269',
    price: '149.43',
    warranty: null,
    tax: '4',
    quantity: '0',
    size: '5',
    video_link: '',
    tags: '["""","Cutting Plier","combination plier","pye"]',
    attributes: [],
    variants: [],
    more_images: [
      'https://pratham.markletech.com/uploads/products/1746254128_Adjustable Wrench toolimax.jpg',
    ],
    status: 'true',
    created_at: '2025-05-03 12:05:28',
    updated_at: '2025-05-17 19:53:16',
    products_branch: '[]',
    best_products: true,
    units: 'Pcs',
    brand: {
      id: '6',
      name: 'Pye',
      image: 'https://pratham.markletech.com/Pye Logo.jpg',
      discount: '5',
      status: 'true',
    },
    categories: [],
  },
  {
    id: '9',
    products_id: '39126',
    product_name: 'testing',
    product_system_name: 'testing',
    hsn_code: 'testing',
    description: '<p>sxz</p>',
    extra_description: '<p>xcsxz</p>',
    stock_discount: '50',
    stock: '40',
    display_image:
      'https://pratham.markletech.com/uploads/products/1747223792_Group 192.png',
    mrp: '20',
    price: '50',
    warranty: {
      id: '2',
      title: '6 Months',
      image: '',
      status: 'true',
      created_at: '2025-04-15 12:40:09',
      updated_at: '2025-05-03 11:35:10',
    },
    tax: '2',
    quantity: '50',
    size: '70',
    video_link: '',
    tags: '"saz,dsxz"',
    attributes: [
      { label: 'xsazxs', value: 'saz' },
      { label: 'sxz', value: 'xz' },
    ],
    variants: [
      {
        id: '11',
        variant_id: 'VAR7756',
        products_id: '9',
        details: {
          variant_id: 'VAR7756',
          psn: '1',
          size: '1',
          quantity: '1',
          mrp: '1',
          price: '1',
          stock: '1',
          stock_discount: '1',
        },
        created_at: '2025-05-14 17:26:32',
      },
      {
        id: '12',
        variant_id: 'VAR7182',
        products_id: '9',
        details: {
          variant_id: 'VAR7182',
          psn: '2',
          size: '2',
          quantity: '2',
          mrp: '2',
          price: '2',
          stock: '2',
          stock_discount: '2',
        },
        created_at: '2025-05-14 17:26:32',
      },
      {
        id: '13',
        variant_id: 'VAR5840',
        products_id: '9',
        details: {
          variant_id: 'VAR5840',
          psn: '3',
          size: '3',
          quantity: '3',
          mrp: '3',
          price: '3',
          stock: '3',
          stock_discount: '3',
        },
        created_at: '2025-05-14 17:26:32',
      },
    ],
    more_images: [
      'https://pratham.markletech.com/uploads/products/1747223792_undraw_not_found_re_bh2e 1.png',
      'https://pratham.markletech.com/uploads/products/1747223792_Group 192.png',
      'https://pratham.markletech.com/uploads/products/1747223792_WhatsApp Image 2025-04-17 at 17.04.33 (1).jpeg',
      'https://pratham.markletech.com/uploads/products/1747223792_vdgwe4585.webp',
      'https://pratham.markletech.com/uploads/products/1747223792_pfkd4924.webp',
      'https://pratham.markletech.com/uploads/products/1747223792_ujrge8733.webp',
    ],
    status: 'true',
    created_at: '2025-05-14 17:26:32',
    updated_at: '2025-05-15 17:28:31',
    products_branch: '["Nelamangala","Whitefield"]',
    best_products: true,
    units: 'Doz',
    brand: {
      id: '4',
      name: 'Cumi',
      image: 'https://pratham.markletech.com/CUMI Logo.jpg',
      discount: '7.5',
      status: 'true',
    },
    categories: [
      {
        id: '3',
        name: 'Bits',
        image: 'https://pratham.markletech.com/uploads/categories/Bits.webp',
      },
      {
        id: '5',
        name: 'Spanners & Wrenches',
        image: 'https://pratham.markletech.com/uploads/categories/Spanners.png',
      },
      {
        id: '7',
        name: 'Papers',
        image: 'https://pratham.markletech.com/uploads/categories/Paper.jpg',
      },
    ],
  },
  {
    id: '10',
    products_id: '64396',
    product_name: 'Lock - Brass Finish',
    product_system_name: 'x',
    hsn_code: '83011000',
    description: '<p>Branded Locks with Brass finish</p>',
    extra_description: '<p><br></p>',
    stock_discount: '3',
    stock: '60',
    display_image:
      'https://pratham.markletech.com/uploads/products/1747492299_PHOTO-2024-10-09-18-50-51 2.jpg',
    mrp: '',
    price: '500',
    warranty: {
      id: '2',
      title: '6 Months',
      image: '',
      status: 'true',
      created_at: '2025-04-15 12:40:09',
      updated_at: '2025-05-03 11:35:10',
    },
    tax: '4',
    quantity: '0',
    size: '6',
    video_link: '',
    tags: '"Lock,Locks"',
    attributes: [],
    variants: [
      {
        id: '18',
        variant_id: 'Lock Caltex Premium 40mm ',
        products_id: '10',
        details: {
          psn: 'Lock Caltex Premium 40mm  4 Keys',
          size: '6',
          quantity: '',
          mrp: '150',
          price: '96.05',
          stock: '',
          stock_discount: '',
        },
        created_at: '2025-05-17 20:01:39',
      },
      {
        id: '19',
        variant_id: 'Lock Caltex Premium 50mm ',
        products_id: '10',
        details: {
          psn: 'Lock Caltex Premium 50mm 4 Keys',
          size: '6',
          quantity: '',
          mrp: '200',
          price: '137.89',
          stock: '',
          stock_discount: '',
        },
        created_at: '2025-05-17 20:01:39',
      },
      {
        id: '20',
        variant_id: 'Lock Caltex Premium 63mm ',
        products_id: '10',
        details: {
          psn: 'Lock Caltex Premium 63mm  4 Keys',
          size: '6',
          quantity: '',
          mrp: '250',
          price: '176.89',
          stock: '',
          stock_discount: '',
        },
        created_at: '2025-05-17 20:01:39',
      },
    ],
    more_images: [
      'https://pratham.markletech.com/uploads/products/1747492299_PHOTO-2024-10-09-18-50-53.jpg',
    ],
    status: 'true',
    created_at: '2025-05-17 20:01:39',
    updated_at: '2025-05-17 20:06:54',
    products_branch: '["Nelamangala","Whitefield"]',
    best_products: true,
    units: 'Pcs',
    brand: {
      id: '1',
      name: 'Caltex',
      image: 'https://pratham.markletech.com/caltex Logo.jpg',
      discount: '5',
      status: 'true',
    },
    categories: [
      {
        id: '10',
        name: 'Locks',
        image: 'https://pratham.markletech.com/uploads/categories/Lock.png',
      },
    ],
  },
  {
    id: '1',
    products_id: '29372',
    product_name: 'Angle Grinder GWS 600',
    product_system_name: 'Angle Grinder Machine Bosch - GWS 600',
    hsn_code: '84672900',
    description:
      '<h1><strong>GWS 600 Professional</strong></h1><h3><strong>Powerful and reliable tool for tradesmen</strong></h3><ul><li>Good handling due to ergonomically adapted housing</li><li>Spindle lock for easy disc change</li></ul>',
    extra_description: '<p><br></p>',
    stock_discount: '0',
    stock: '0',
    display_image:
      'https://pratham.markletech.com/uploads/products/1746253763_Angle Grinder Machine Bosch - GWS 800.png',
    mrp: '4100',
    price: '2033',
    warranty: {
      id: '3',
      title: '1 Year',
      image: '',
      status: 'true',
      created_at: '2025-05-03 11:35:19',
      updated_at: '2025-05-03 11:35:19',
    },
    tax: '4',
    quantity: '0',
    size: '5',
    video_link: 'https://www.youtube.com/watch?v=mGSi4PkoatI',
    tags: '["""","Angle Grinder","Angle","Grinder","Grinder Machine","Bosch Grinder"]',
    attributes: [
      { label: 'Rated input power', value: '670 W' },
      { label: 'No-load speed', value: '11,000 rpm' },
      { label: 'Disc diameter', value: '100mm' },
      { label: 'Grinding spindle thread', value: 'M10' },
      { label: 'Weight', value: '1.5 kg' },
      { label: 'Switch', value: 'Lockable Switch' },
      { label: 'Power Type', value: 'Corded' },
    ],
    variants: [],
    more_images: [
      'https://pratham.markletech.com/uploads/products/1746253763_gws6001.webp',
      'https://pratham.markletech.com/uploads/products/1746284035_PHOTO-2024-10-09-18-48-13.jpg',
      'https://pratham.markletech.com/uploads/products/1746507405_PE L3.PNG',
    ],
    status: 'true',
    created_at: '2025-05-03 11:59:23',
    updated_at: '2025-05-10 11:37:24',
    products_branch: '3',
    best_products: false,
    units: 'Pcs',
    brand: {
      id: '3',
      name: 'Bosch',
      image: 'https://pratham.markletech.com/BOSCH LOGO1.png',
      discount: '4',
      status: 'true',
    },
    categories: [],
  },
  {
    id: '3',
    products_id: '77486',
    product_name: 'Granite Bit 2 in 1',
    product_system_name: '',
    hsn_code: '82074090',
    description:
      '<p>Granite Core Bit Used for drilled into Marble and Granite</p><p>Carbite Tip</p><p>High Quality</p>',
    extra_description: '<p><br></p>',
    stock_discount: '0',
    stock: '0',
    display_image:
      'https://pratham.markletech.com/uploads/products/1746254678_Caltex granite bit.PNG',
    mrp: '5',
    price: '500',
    warranty: null,
    tax: '4',
    quantity: '0',
    size: '',
    video_link: '',
    tags: '""',
    attributes: [],
    variants: [],
    more_images: [],
    status: 'true',
    created_at: '2025-05-03 12:14:38',
    updated_at: '2025-05-15 17:31:31',
    products_branch: '',
    best_products: false,
    units: 'Pcs',
    brand: {
      id: '1',
      name: 'Caltex',
      image: 'https://pratham.markletech.com/caltex Logo.jpg',
      discount: '5',
      status: 'true',
    },
    categories: [],
  },
];

export const indianStates = [
  { label: 'Andhra Pradesh', value: 'andhra pradesh' },
  { label: 'Arunachal Pradesh', value: 'arunachal pradesh' },
  { label: 'Assam', value: 'assam' },
  { label: 'Bihar', value: 'bihar' },
  { label: 'Chhattisgarh', value: 'chhattisgarh' },
  { label: 'Goa', value: 'goa' },
  { label: 'Gujarat', value: 'gujarat' },
  { label: 'Haryana', value: 'haryana' },
  { label: 'Himachal Pradesh', value: 'himachal pradesh' },
  { label: 'Jharkhand', value: 'jharkhand' },
  { label: 'Karnataka', value: 'karnataka' },
  { label: 'Kerala', value: 'kerala' },
  { label: 'Madhya Pradesh', value: 'madhya pradesh' },
  { label: 'Maharashtra', value: 'maharashtra' },
  { label: 'Manipur', value: 'manipur' },
  { label: 'Meghalaya', value: 'meghalaya' },
  { label: 'Mizoram', value: 'mizoram' },
  { label: 'Nagaland', value: 'nagaland' },
  { label: 'Odisha', value: 'odisha' },
  { label: 'Punjab', value: 'punjab' },
  { label: 'Rajasthan', value: 'rajasthan' },
  { label: 'Sikkim', value: 'sikkim' },
  { label: 'Tamil Nadu', value: 'tamil nadu' },
  { label: 'Telangana', value: 'telangana' },
  { label: 'Tripura', value: 'tripura' },
  { label: 'Uttar Pradesh', value: 'uttar pradesh' },
  { label: 'Uttarakhand', value: 'uttarakhand' },
  { label: 'West Bengal', value: 'west bengal' },
  { label: 'Andaman and Nicobar Islands', value: 'andaman and nicobar islands' },
  { label: 'Chandigarh', value: 'chandigarh' },
  { label: 'Dadra and Nagar Haveli and Daman and Diu', value: 'dadra and nagar haveli and daman and diu' },
  { label: 'Delhi', value: 'delhi' },
  { label: 'Jammu and Kashmir', value: 'jammu and kashmir' },
  { label: 'Ladakh', value: 'ladakh' },
  { label: 'Lakshadweep', value: 'lakshadweep' },
  { label: 'Puducherry', value: 'puducherry' }
];

